[project]
name = "autoencoder"
version = "0.1.0"
description = "An end-to-end neural network based auto-encoder for an OFDM wireless transmission system."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch",
    "numpy",
    "matplotlib",
    "tqdm",
]
